catch(int err) is 0
